<?php<?php







































































































































































echo "<p><strong>Bravo ! Passez au Jour 7 🎉</strong></p>";echo "</ul>";echo "<li>✅ Vous pouvez implémenter des méthodes métier</li>";echo "<li>✅ Vous comprenez l'encapsulation</li>";echo "<li>✅ Vous savez utiliser les getters et setters</li>";echo "<li>✅ Vous maîtrisez la création de classes</li>";echo "<ul>";echo "<p>Une fois tous les tests passés :</p>";echo "<h2>📊 Bilan</h2>";// ====================================// BILAN FINAL// ====================================echo "<hr>";}    echo "❌ Erreur : " . $e->getMessage() . "<br>";} catch (Exception $e) {    echo "⚠️ Décommenter le code quand tous les getters/setters sont implémentés<br>";        */    echo "✅ Tous les setters fonctionnent !<br>";        }        echo "✅ Stock détecté comme faible (correct)<br>";    if ($produit->stockFaible()) {        echo "Nouveau stock : " . $produit->getStock() . " unités<br>";    $produit->setStock(5);        echo "Nouveau prix : " . $produit->getPrix() . " €<br>";    $produit->setPrix(39.99);    /*    // TODO: Décommenter quand tous les getters/setters sont implémentéstry {echo "<h2>Test 5 : Getters et Setters</h2>";// ====================================// TEST 5 : Getters et Setters// ====================================echo "<hr>";}    echo "❌ Erreur : " . $e->getMessage() . "<br>";} catch (Exception $e) {    echo "⚠️ Décommenter le code quand appliquerRemise() est implémentée<br>";        */    }        echo "❌ Erreur de calcul. Attendu : 26.99, Obtenu : $prixAvecRemise<br>";    } else {        echo "✅ Calcul de remise correct !<br>";    if (abs($prixAvecRemise - 26.99) < 0.01) {        echo "Prix avec 10% de remise : " . number_format($prixAvecRemise, 2) . " €<br>";    $prixAvecRemise = $produit->appliquerRemise(10); // 10% de remise    /*    // TODO: Décommenter quand appliquerRemise() est implémentéetry {echo "<h2>Test 4 : Application d'une remise</h2>";// ====================================// TEST 4 : Application d'une remise// ====================================echo "<hr>";}    echo "❌ Erreur : " . $e->getMessage() . "<br>";} catch (Exception $e) {    echo "⚠️ Décommenter le code quand estDisponible() et stockFaible() sont implémentées<br>";        */    }        echo "✅ Stock suffisant<br>";    } else {        echo "⚠️ Stock faible (< 10)<br>";    if ($produit->stockFaible()) {        }        echo "❌ Produit en rupture<br>";    } else {        echo "✅ Produit en stock<br>";    if ($produit->estDisponible()) {    /*    // TODO: Décommenter quand les méthodes sont implémentéestry {echo "<h2>Test 3 : Vérification du stock</h2>";// ====================================// TEST 3 : Vérification du stock// ====================================echo "<hr>";}    echo "❌ Erreur : " . $e->getMessage() . "<br>";} catch (Exception $e) {    echo "⚠️ Décommenter le code quand calculerPrixTTC() est implémentée<br>";        */    }        echo "❌ Erreur de calcul. Attendu : 35.99, Obtenu : $prixTTC<br>";    } else {        echo "✅ Calcul correct !<br>";    if ($prixTTC === 35.99) {        echo "Prix TTC (20%) : " . number_format($prixTTC, 2) . " €<br>";    $prixTTC = $produit->calculerPrixTTC();    /*    // TODO: Décommenter quand calculerPrixTTC() est implémentétry {echo "<h2>Test 2 : Calcul du prix TTC</h2>";// ====================================// TEST 2 : Calcul du prix TTC// ====================================echo "<hr>";}    echo "❌ Erreur : " . $e->getMessage() . "<br>";} catch (Exception $e) {    echo "⚠️ Décommenter le code quand le constructeur est implémenté<br>";        */    echo "Prix HT : " . $produit->getPrix() . " €<br>";    echo "✅ Produit créé : " . $produit->getNom() . "<br>";        );        image: "tshirt.jpg"        categorie: "vetements",        stock: 150,        prix: 29.99,        description: "Un super t-shirt",        nom: "T-shirt Premium",    $produit = new Produit(    /*    // TODO: Décommenter quand le constructeur est implémentétry {echo "<h2>Test 1 : Création d'un produit</h2>";// ====================================// TEST 1 : Création d'un produit// ====================================echo "<hr>";echo "<h1>🧪 Tests Jour 6 - Classe Produit</h1>";use App\Models\Produit;require_once __DIR__ . '/vendor/autoload.php'; */ * Décommenter les lignes au fur et à mesure de la complétion des exercices *  * Fichier de test - Jour 6/**
