<!DOCTYPE html><?php






































































































</html></body>    <script src="/js/panier.js"></script>    <script src="/js/app.js"></script>    <!-- JavaScript -->    </footer>        </div>            </div>                <p>&copy; <?= date('Y') ?> Boutique PHP - Projet de formation</p>            <div class="footer__bottom">                        </div>                </div>                    </form>                        <button type="submit" class="btn btn-primary mt-2">S'inscrire</button>                        <input type="email" placeholder="Votre email" class="form-input">                    <form>                    <p>Recevez nos offres exclusives</p>                    <h3>Newsletter</h3>                <div class="footer__section">                                </div>                    </ul>                        <li><a href="#">Retours</a></li>                        <li><a href="#">Livraison</a></li>                        <li><a href="#">Contact</a></li>                        <li><a href="#">FAQ</a></li>                    <ul>                    <h3>Aide</h3>                <div class="footer__section">                                </div>                    </ul>                        <li><a href="#">Mentions légales</a></li>                        <li><a href="#">Nos valeurs</a></li>                        <li><a href="#">Qui sommes-nous ?</a></li>                    <ul>                    <h3>À propos</h3>                <div class="footer__section">            <div class="footer__content">        <div class="container">    <footer class="footer">    <!-- Footer -->    </main>        <?= $content ?? '' ?>    <main>    <!-- Contenu principal -->    <?php endif; ?>        </div>            </div>                <?= e($errorMsg) ?>            <div class="alert alert-error" data-auto-close="5000">        <div class="container">    <?php if ($errorMsg = flash('error')): ?>    <?php endif; ?>        </div>            </div>                <?= e($successMsg) ?>            <div class="alert alert-success" data-auto-close="5000">        <div class="container">    <?php if ($successMsg = flash('success')): ?>    <!-- Alertes Flash -->    </header>        </div>            </nav>                <a href="/admin">Admin</a>                </a>                    <span class="header__cart-badge">0</span>                    🛒 Panier                <a href="/panier" class="header__cart">                <a href="/catalogue">Catalogue</a>                <a href="/">Accueil</a>            <nav class="header__nav">                        </div>                </form>                           value="<?= e($_GET['recherche'] ?? '') ?>">                    <input type="text" name="recherche" placeholder="Rechercher un produit..."                 <form action="/catalogue" method="GET">            <div class="header__search">                        <a href="/" class="header__logo">🛍️ PHP Store</a>        <div class="container header__content">    <header class="header">    <!-- Header --><body></head>    <link rel="stylesheet" href="/css/responsive.css">    <link rel="stylesheet" href="/css/style.css">    <!-- CSS -->        <title><?= $title ?? 'Boutique PHP' ?></title>    <meta name="viewport" content="width=device-width, initial-scale=1.0">    <meta charset="UTF-8"><head><html lang="fr">
