<?php<?php












































































































































































}    }        redirect('/admin/produits');                }            flash('error', 'Erreur lors de la suppression');        } else {            flash('success', 'Produit supprimé');        if ($success) {                $success = $this->produitRepo->delete($id);                }            return;            redirect('/admin/produits');        if (!isPost()) {                // TODO JOUR 9: Supprimer le produit    {    public function delete(int $id): void     */     * @return void     * @param int $id     *      * Route: POST /admin/produits/{id}/supprimer     * Supprimer un produit    /**        }        redirect('/admin/produits');        flash('success', 'Produit modifié avec succès !');                // TODO: Implémenter la mise à jour                }            return;            redirect("/admin/produits/{$id}/modifier");        if (!isPost()) {                // TODO JOUR 9: Traiter la mise à jour    {    public function update(int $id): void     */     * @return void     * @param int $id     *      * Route: POST /admin/produits/{id}/modifier     * Mettre à jour un produit    /**        }        ]);            'action' => 'edit'            'produit' => $produit,        view('admin.produits.form', [                }            return;            redirect('/admin/produits');            flash('error', 'Produit non trouvé');        if (!$produit) {                $produit = $this->produitRepo->findById($id);                // TODO JOUR 9: Afficher le formulaire d'édition    {    public function edit(int $id): void     */     * @return void     * @param int $id     *      * Route: GET /admin/produits/{id}/modifier     * Formulaire d'édition    /**        }        redirect('/admin/produits');        flash('success', 'Produit créé avec succès !');                // TODO: Implémenter la création        // Créer le produit                }            return;            back();            flash('error', 'Erreurs de validation');            // TODO: Gérer les erreurs        if (!empty($errors)) {                ]);            'categorie' => 'required'            'stock' => 'required|numeric',            'prix' => 'required|numeric',            'nom' => 'required|min:3|max:255',        $errors = validate($_POST, [        // Validation                }            return;            redirect('/admin/produits/nouveau');        if (!isPost()) {                // 4. Rediriger avec message de succès        // 3. Enregistrer avec le repository        // 2. Créer un objet Produit        // 1. Valider les données POST        // TODO JOUR 9: Traiter l'enregistrement    {    public function store(): void     */     * @return void     *      * Route: POST /admin/produits/nouveau     * Enregistrer un nouveau produit    /**        }        ]);            'action' => 'create'            'produit' => null,        view('admin.produits.form', [                // TODO JOUR 9: Afficher le formulaire de création    {    public function create(): void     */     * @return void     *      * Route: GET /admin/produits/nouveau     * Formulaire de création    /**        }        ]);            'produits' => $produits        view('admin.produits.index', [                $produits = $this->produitRepo->findAll();                // TODO JOUR 9: Afficher la liste des produits pour l'admin    {    public function index(): void     */     * @return void     *      * Route: GET /admin/produits     * Liste des produits (admin)    /**        }        $this->produitRepo = new ProduitRepository();    {    public function __construct()        private ProduitRepository $produitRepo;{class AdminProduitController */ * @version 1.0 * @author Apprenant *  * EXERCICE JOUR 9 : Compléter ce contrôleur *  * Contrôleur Admin Produit - Gestion CRUD des produits (backoffice)/**use App\Models\Produit;use App\Repositories\ProduitRepository;namespace App\Controllers\Admin;
