<?php<?php



























];    ],        ],            'collation' => 'utf8mb4_unicode_ci',            'charset' => 'utf8mb4',            'password' => env('DB_PASSWORD', ''),            'username' => env('DB_USER', 'root'),            'database' => env('DB_NAME', 'boutique'),            'port' => env('DB_PORT', '3306'),            'host' => env('DB_HOST', 'localhost'),            'driver' => 'mysql',        'mysql' => [                ],            'database' => env('DB_DATABASE', 'database/boutique.db'),            'driver' => 'sqlite',        'sqlite' => [    'connections' => [        'default' => env('DB_CONNECTION', 'sqlite'),return [ */ * Configuration de la base de données/**
