<?php<?php












































}    }        ]);            'produits' => $produits        view('home.index', [        // Afficher la vue                $produits = []; // TODO: Implémenter        // Récupérer les 4 derniers produits                // 3. Passer les données à la vue avec view()        // 2. Limiter à 4 produits (array_slice)        // 1. Utiliser $this->produitRepo->findAll() pour récupérer les produits        // TODO JOUR 9: Récupérer les produits vedettes    {    public function index(): void     */     * @return void     *      * Afficher la page d'accueil    /**        }        $this->produitRepo = new ProduitRepository();    {    public function __construct()        private ProduitRepository $produitRepo;{class HomeController */ * @version 1.0 * @author Apprenant *  * EXERCICE JOUR 9 : Compléter ce contrôleur *  * Contrôleur Home - Page d'accueil/**use App\Repositories\ProduitRepository;namespace App\Controllers;
