<?php<?php














































































































































}    }        ]);            'tva' => $this->panier->calculerTVA()            'sousTotal' => $this->panier->calculerSousTotal(),            'total' => $this->panier->calculerTotal(),            'produits' => $produits,        echo json_encode([                // TODO: Charger les détails de chaque produit                $produits = [];        $items = $this->panier->getItems();                header('Content-Type: application/json');                // Pour l'affichage dynamique côté front        // TODO JOUR 9: Retourner les détails du panier en JSON    {    public function details(): void     */     * @return void     *      * Route: POST /api/panier/details     * API: Récupérer les détails du panier (utilisé par JS)    /**        }        redirect('/panier');        flash('success', 'Panier vidé');                setSession('panier', $this->panier);        $this->panier->vider();                // TODO JOUR 9: Vider le panier complètement    {    public function vider(): void     */     * @return void     *      * Route: POST /panier/vider     * Vider le panier    /**        }        redirect('/panier');        flash('success', 'Produit retiré du panier');                // TODO: Implémenter le retrait                $produitId = (int) input('produit_id');                }            return;            redirect('/panier');        if (!isPost()) {                // TODO JOUR 9: Retirer du panier    {    public function retirer(): void     */     * @return void     *      * Route: POST /panier/retirer     * Retirer un produit du panier    /**        }        back();        flash('success', 'Produit ajouté au panier !');                // TODO: Implémenter l'ajout                $quantite = (int) input('quantite', 1);        $produitId = (int) input('produit_id');                }            return;            redirect('/catalogue');        if (!isPost()) {                // 5. Rediriger avec message de succès        // 4. Sauvegarder en session        // 3. Ajouter au panier        // 2. Charger le produit depuis la BDD        // 1. Récupérer produit_id et quantite depuis POST        // TODO JOUR 7 & 9: Ajouter au panier    {    public function ajouter(): void     */     * @return void     *      * Route: POST /panier/ajouter     * Ajouter un produit au panier    /**        }        ]);            'panier' => $this->panier        view('panier.index', [                // TODO JOUR 9: Afficher la page panier    {    public function index(): void     */     * @return void     *      * Route: GET /panier     * Afficher le panier    /**        }        $this->panier = session('panier');                }            setSession('panier', new Panier());        if (!session('panier')) {        // Récupérer le panier depuis la session                $this->produitRepo = new ProduitRepository();    {    public function __construct()        private Panier $panier;    private ProduitRepository $produitRepo;{class PanierController */ * @version 1.0 * @author Apprenant *  * EXERCICE JOUR 7 & 9 : Compléter ce contrôleur *  * Contrôleur Panier - Gestion du panier d'achats/**use App\Repositories\ProduitRepository;use App\Models\Panier;namespace App\Controllers;
